<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Appendix F — Change Log – Augmented vs. Traditional Instruction in Manufacturing Assembly</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../_apps/31a-irb.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-0cda25dcbb8fe09c7138904322940710.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-b686cc021c183984fa51c053ac765ee9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../css/custom.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_apps/32b-contributions.html">Appendices</a></li><li class="breadcrumb-item"><a href="../_apps/39i-changelog.html"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Change Log</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Augmented vs.&nbsp;Traditional Instruction in Manufacturing Assembly</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abstract</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_front/13-acknowledgements-html.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Acknowledgements</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/21-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/22-lit_review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Literature Review</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/23-prob_statement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Problem Statement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/24-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/25-results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Results</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/26-conclusions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Conclusions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_chaps/28-references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_apps/32b-contributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Team Contribution Matrix</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_apps/35e-videotools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Video Tool Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_apps/36f-videoproc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Video Processing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_apps/38h-dataorg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Data Organization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_apps/31a-irb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Institutional Review Board Approval</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../_apps/39i-changelog.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Change Log</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#change-register" id="toc-change-register" class="nav-link active" data-scroll-target="#change-register"><span class="header-section-number">F.1</span> Change Register</a>
  <ul class="collapse">
  <li><a href="#v1.1" id="toc-v1.1" class="nav-link" data-scroll-target="#v1.1"><span class="header-section-number">F.1.1</span> v1.1</a></li>
  <li><a href="#v1.1.1" id="toc-v1.1.1" class="nav-link" data-scroll-target="#v1.1.1"><span class="header-section-number">F.1.2</span> v1.1.1</a></li>
  </ul></li>
  <li><a href="#correction-notes" id="toc-correction-notes" class="nav-link" data-scroll-target="#correction-notes"><span class="header-section-number">F.2</span> Correction Notes</a>
  <ul class="collapse">
  <li><a href="#sec-v1-1-h3b-note" id="toc-sec-v1-1-h3b-note" class="nav-link" data-scroll-target="#sec-v1-1-h3b-note"><span class="header-section-number">F.2.1</span> v1.1 H3b Interpretation Correction Note</a></li>
  <li><a href="#sec-v1-1-reliance-note" id="toc-sec-v1-1-reliance-note" class="nav-link" data-scroll-target="#sec-v1-1-reliance-note"><span class="header-section-number">F.2.2</span> v1.1.1 H2b Reliance Direction Correction Note</a></li>
  <li><a href="#sec-v1-1-boot-note" id="toc-sec-v1-1-boot-note" class="nav-link" data-scroll-target="#sec-v1-1-boot-note"><span class="header-section-number">F.2.3</span> v1.1.1 Bootstrap Replication Seeding Correction Note</a></li>
  </ul></li>
  <li><a href="#interpretation-boundaries" id="toc-interpretation-boundaries" class="nav-link" data-scroll-target="#interpretation-boundaries"><span class="header-section-number">F.3</span> Interpretation Boundaries</a></li>
  <li><a href="#intentional-deferrals" id="toc-intentional-deferrals" class="nav-link" data-scroll-target="#intentional-deferrals"><span class="header-section-number">F.4</span> Intentional Deferrals</a></li>
  <li><a href="#repository-diff" id="toc-repository-diff" class="nav-link" data-scroll-target="#repository-diff"><span class="header-section-number">F.5</span> Repository Diff</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../_apps/32b-contributions.html">Appendices</a></li><li class="breadcrumb-item"><a href="../_apps/39i-changelog.html"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Change Log</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-v1-1-changelog" class="quarto-section-identifier">Appendix F — Change Log</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This appendix records the exact changes applied in the <code>v1.1</code> release relative to the as-submitted defended dissertation, followed by the additional corrections made in the subsequent <code>v1.1.1</code> point release. These corrections are reflected in the current HTML and PDF renders generated from the same source. The list below is intended to be complete for the changes made in these passes. No new data were collected and no new analyses were introduced.</p>
<section id="change-register" class="level2" data-number="F.1">
<h2 data-number="F.1" class="anchored" data-anchor-id="change-register"><span class="header-section-number">F.1</span> Change Register</h2>
<p>Corrections are grouped by release below. The key interpretive and procedural changes are described more fully in the correction notes that follow this register.</p>
<section id="v1.1" class="level3" data-number="F.1.1">
<h3 data-number="F.1.1" class="anchored" data-anchor-id="v1.1"><span class="header-section-number">F.1.1</span> v1.1</h3>
<div style="font-size: 0.85em;">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 32%">
<col style="width: 28%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Location</th>
<th>Issue in defended release</th>
<th>Correction</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Literature Review footnote</td>
<td>Unresolved <code>*THEORY SECTION*</code> placeholder</td>
<td>Replaced with a direct cross-reference to the later theory section (<code>@sec-theory</code>)</td>
<td>Remove draft residue and point readers to the actual theory discussion</td>
</tr>
<tr class="even">
<td>Methods, retention hypotheses</td>
<td>Leaked TODO rendered in public output because the hiding wrapper was misspelled as <code>contents-hidden</code></td>
<td>Removed the leaked note and rewrote the subsection as regular prose</td>
<td>Remove visible draft residue and make the subsection publication-safe</td>
</tr>
<tr class="odd">
<td>Methods, retention hypotheses</td>
<td>Retention was stated in Methods as <code>H3a: Change in OEE varies with treatment</code>, while defended Results evaluated retention using changes in task completion time and uncorrected error count</td>
<td>Updated the Methods block so retention is stated and tested in terms of <code>TCT</code> and <code>UCE</code>, matching the defended Results chapter</td>
<td>Reconcile Methods with the already-defended analysis without introducing a new retention analysis</td>
</tr>
<tr class="even">
<td>Methods, legacy analysis-plan wording</td>
<td>A few remaining Methods passages still reflected the original analysis plan, including references to OEE in retention context and hardware-specific treatment labels</td>
<td>Added footnotes clarifying the final defended analysis path and the equivalence of <code>HMDAR/HMDMR</code> with the simpler <code>AR/MR</code> labels used later in the manuscript</td>
<td>Improve transparency around residual legacy wording without rewriting the defended prose</td>
</tr>
<tr class="odd">
<td>Results, H2b Q-Q plot</td>
<td>Placeholder subtitle <code>subtitle...</code></td>
<td>Replaced with <code>PWI and PAR show the clearest departures from normality</code></td>
<td>Remove placeholder text and summarize the displayed pattern</td>
</tr>
<tr class="even">
<td>Results, H2b bootstrap interpretation</td>
<td>Hidden <code>TODO: FIX THIS</code> remained in source and the visible typo <code>more than than</code> remained in prose</td>
<td>Removed the hidden note, corrected the typo to <code>more than</code>, and softened the sentence to report what the estimates suggest rather than overstate certainty</td>
<td>Editorial cleanup and more proportionate interpretation</td>
</tr>
<tr class="odd">
<td>Results, H1b model-comparison table</td>
<td><code>compare_performance()</code> emitted stdout into the rendered body text before the table</td>
<td>Captured the emitted stdout so it no longer renders; the comparison table itself is unchanged</td>
<td>Remove render artifact without changing the analysis</td>
</tr>
<tr class="even">
<td>Results, H1b model-comparison table</td>
<td>Candidate model 4 showed blank conditional <span class="math inline">\(R^2\)</span> and ICC values without explanation</td>
<td>Added an explicit note that candidate model 4 produced a singular fit, so conditional <span class="math inline">\(R^2\)</span> and ICC were unavailable</td>
<td>Make the omitted values transparent to readers</td>
</tr>
<tr class="odd">
<td>Results, sample and exclusion notes</td>
<td>The scope of the participant 1063 exclusion, the recall analysis sample, and the <code>H2b</code>-specific outlier removal were implicit in the defended text</td>
<td>Added footnotes clarifying the 1063 exclusion, the recall sample composition, and the fact that the <code>H2b</code> outlier removal affected only that analysis; corrected a nearby typographical error in the <code>H2b</code> outlier paragraph</td>
<td>Improve transparency around analysis-specific sample definitions without revising the defended narrative</td>
</tr>
<tr class="even">
<td>Results, reporting corrections</td>
<td>A demographics sentence reused the Lego p-value for Education; one H3a sentence mismatched <code>iUCE</code> with an <code>iTCT</code> figure; one H3b figure caption used <code>Uncounted</code> instead of <code>Uncorrected</code>; and one typo read <code>revering</code></td>
<td>Corrected the Education p-value reference, aligned the H3a sentence with the <code>iTCT</code> figure, standardized the H3b caption to <code>Uncorrected</code>, and fixed the typo to <code>reversing</code></td>
<td>Correct concrete reporting and labeling errors without changing the underlying analyses</td>
</tr>
<tr class="odd">
<td>Results and Conclusions, H3b interpretation</td>
<td>The defended text interprets the selected additive ZINB retention model as if gap effects were additive and treatment-specific in slope</td>
<td>Added footnotes in Results and Conclusions that point to <a href="#sec-v1-1-h3b-note" class="quarto-xref"><span>Section F.2.1</span></a>, where the interpretive correction and its implications are discussed without rewriting the defended narrative in place</td>
<td>Make a substantive interpretive correction transparent while preserving the defended text</td>
</tr>
<tr class="even">
<td>Landing page, HTML edition</td>
<td>Public HTML opened directly to the abstract, without a visible dissertation identity block or committee listing</td>
<td>Added an HTML-only dissertation identification block before the abstract, including title, author, degree context, date, and approved committee list</td>
<td>Make the HTML edition legible as a dissertation when opened directly</td>
</tr>
<tr class="odd">
<td>Landing page, HTML edition</td>
<td>Public HTML did not visibly distinguish the corrected <code>v1.1</code> release from the as-defended dissertation or provide a direct path to the project source</td>
<td>Added an HTML-only <code>v1.1</code> callout on the landing page with direct links to <a href="#sec-v1-1-changelog" class="quarto-xref"><span>Appendix F</span></a>, the as-defended dissertation PDF on GitHub, and the project repository on GitHub</td>
<td>Make release status, provenance, and source access clear at the point of entry</td>
</tr>
<tr class="even">
<td>Appendix D, Data Organization</td>
<td>Visible TODO lines in public appendix text</td>
<td>Removed the TODO lines</td>
<td>Remove visible draft residue</td>
</tr>
<tr class="odd">
<td>Appendix E, Institutional Review Board Approval</td>
<td>Appendix lead-in did not point readers to the defended public artifact</td>
<td>Replaced the lead-in with a direct link to the standalone as-submitted IRB packet on GitHub</td>
<td>Improve traceability to the defended IRB materials</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="v1.1.1" class="level3" data-number="F.1.2">
<h3 data-number="F.1.2" class="anchored" data-anchor-id="v1.1.1"><span class="header-section-number">F.1.2</span> v1.1.1</h3>
<div style="font-size: 0.85em;">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 32%">
<col style="width: 28%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Location</th>
<th>Issue in defended release</th>
<th>Correction</th>
<th>Reason</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Results <span class="math inline">\(H_{2b}\)</span> and Conclusions (recall)</td>
<td>The recall reliance comparison is stated with its direction reversed, describing the augmented conditions as reducing paper reliance relative to PWI, accompanied by two misprinted magnitudes (0.686, 0.612)</td>
<td>Added a correction note (<a href="#sec-v1-1-reliance-note" class="quarto-xref"><span>Section F.2.2</span></a>) and footnotes establishing that PWI and PAR showed the lowest paper reliance at recall and the head-mounted AR and MR the highest; <a href="../_chaps/25-results.html#tbl-boot-pwi" class="quarto-xref">Table&nbsp;<span>5.18</span></a> is correct and unchanged</td>
<td>Corrects a directional reporting error that propagated into the recall interpretation and conclusions, without altering the defended table or the <span class="math inline">\(H_{2b}\)</span> determination</td>
</tr>
<tr class="even">
<td>Results <span class="math inline">\(H_{2a}\)</span> and <span class="math inline">\(H_{2b}\)</span> bootstrap</td>
<td>The complementary bootstrap was described as five replications averaged together, with the across-replication dispersion reported as evidence of stability</td>
<td>Added a correction note (<a href="#sec-v1-1-boot-note" class="quarto-xref"><span>Section F.2.3</span></a>) and a footnote explaining that a seeding error made the five replications identical, so the reported dispersion is structurally zero and the estimates are those of a single bootstrap</td>
<td>Corrects a misleading procedural description; point estimates, intervals, and the <span class="math inline">\(H_{2a}\)</span> and <span class="math inline">\(H_{2b}\)</span> conclusions are unchanged</td>
</tr>
<tr class="odd">
<td>Conclusions, learning results-summary table (<span class="math inline">\(H_{1b}\)</span> row)</td>
<td>The <span class="math inline">\(H_{1b}\)</span> row states the model controlled for “iTCT” (the retention-phase increase in TCT); the defended model controlled for initial TCT (<span class="math inline">\(TCT_0\)</span>)</td>
<td>Added a footnote at <a href="../_chaps/26-conclusions.html#tbl-learn-results-summary" class="quarto-xref">Table&nbsp;<span>6.1</span></a> clarifying that the covariate should be read as the initial TCT (<span class="math inline">\(TCT_0\)</span>); the defended table is left as displayed</td>
<td>Clarifies the covariate label transparently without altering the defended summary table or the <span class="math inline">\(H_{1b}\)</span> determination</td>
</tr>
<tr class="even">
<td>Conclusions, Empirical Contributions</td>
<td>The Empirical Contributions summary groups PAR with PWI as showing higher error rates, contradicting the chapter’s own <span class="math inline">\(H_{1c}\)</span> result and summary table (PAR is statistically low-error, indistinguishable from AR and MR)</td>
<td>Added a footnote at the affected sentence noting that PAR was significantly lower in errors than PWI and groups with the augmented conditions on accuracy. The abstract carries the same augmented-vs-traditional framing on the speed axis (“augmented technologies generally led to … slower initial performance”), where PAR is the analogous fast exception; that statement is reasonably hedged and is left as written</td>
<td>Corrects an internal inconsistency without altering the defended sentence; the <span class="math inline">\(H_{1c}\)</span> determination is unchanged</td>
</tr>
<tr class="odd">
<td>Results, <span class="math inline">\(H_{2a}\)</span> OEE bootstrap discussion</td>
<td>The PWI-MR average OEE difference is misprinted as 0.307; the correct value (the mean of the absolute Mean/Median/HL differences) is 0.614, exactly twice the printed figure</td>
<td>Added a footnote flagging the misprint and the corrected value (0.614); the PWI-PAR (0.687) and PWI-AR (0.585) figures are correct, and once corrected the three PWI-versus-augmented gaps (0.687, 0.585, 0.614) are comparable rather than MR appearing smallest</td>
<td>Corrects a misprinted descriptive statistic; no augmented-vs-augmented difference was significant, so the <span class="math inline">\(H_{2a}\)</span> determination is unchanged</td>
</tr>
<tr class="even">
<td>Results, <span class="math inline">\(H_{3b}\)</span> model table (<a href="../_chaps/25-results.html#tbl-uce-modsum" class="quarto-xref">Table&nbsp;<span>5.24</span></a>)</td>
<td>The “Adj Coef” column halves every coefficient to undo the 2x response scaling, but the treatment coefficients are scale-invariant rate ratios that should not be halved; the PWI-vs-AR factor is stated as 0.197 instead of 0.394</td>
<td>Extended the H3b correction note (<a href="#sec-v1-1-h3b-note" class="quarto-xref"><span>Section F.2.1</span></a>) to explain that the halving applies only to the intercept and that the PWI factor is 0.394</td>
<td>Corrects a coefficient-rescaling error within the already-noted H3b interpretation; sign, significance, and the <span class="math inline">\(H_{3b}\)</span> conclusion are unchanged</td>
</tr>
<tr class="odd">
<td>Results, <span class="math inline">\(H_{2a}\)</span> OEE bootstrap introduction</td>
<td>States that the bootstrap “increases the sample size and statistical power”; resampling does neither, since it reuses the observed data</td>
<td>Extended the bootstrap correction note (<a href="#sec-v1-1-boot-note" class="quarto-xref"><span>Section F.2.3</span></a>) to clarify that resampling improves only the precision of the sampling-distribution estimate, not the effective sample size or power</td>
<td>Corrects a methodological misstatement; the bootstrap is a complementary check and the <span class="math inline">\(H_{2a}\)</span> conclusion is unchanged</td>
</tr>
<tr class="even">
<td>Various (Results)</td>
<td>Low-severity, conclusion-neutral slips: the Poisson model-comparison BIC claim (F-008; inert, both Poisson models are discarded for overdispersion); the iTCT median ordering (F-009; PAR highest, no treatment effect); the H1b fixed-vs-random correlation gloss (F-001; -0.75 vs -0.85, same sign and magnitude); the H1c “IQR and Z-score” wording (F-025; IQR only, a robustness check); the TLX Q2 boundary figures (G-004; off by hundredths, qualitative point holds); and a duplicated SUS figure caption (G-009; readable from its own title). Two bibliography-metadata items were corrected in a Zotero bibliography pass: the four cited skeletal <code>@article</code> stubs that rendered “(n.d.)” (F-034) were retyped as <code>@misc</code> web resources with organization authors, source URLs, and 2022 access dates (publication year left n.d., as these are undated web resources); and the malformed year in the uncited <code>konig2018embod</code> entry (F-035) was corrected to 2018.</td>
<td>Flagged by footnote (F-008, F-009, F-001) or noted here (F-025, G-004, G-009); no defended number or table is altered; F-034 updates only the four affected bibliography entries (organization author, access date, URL) and F-035 is non-rendering</td>
<td>General cleanup of minor reporting and descriptive slips; none affects a hypothesis decision, estimate, test, or conclusion</td>
</tr>
<tr class="odd">
<td>Various (Results, Conclusions, Methods, Problem Statement, Literature Review, change log)</td>
<td>Residual copy and render defects: repeated words, eponym and term misspellings (e.g.&nbsp;“Kruskall-”/“Kurskal-Wallis”, “Heart” for Hart), verb-form slips, a “left-skewed” label that should read “right-skewed”, an orphan “RQ1” label, the affordance name “Egocentric Display” (should be “User-Centric Display”), “System Usability Score” (should be “Scale”), a figure cross-reference and a citation missing their leading “@”, a spurious squared superscript on a negative rank-biserial correlation, and “Appendix Appendix F” double-prints</td>
<td>Corrected each inline in the rendered build</td>
<td>Editorial and render cleanup only; no statistic, value, or claim is affected</td>
</tr>
</tbody>
</table>
</div>
</section>
</section>
<section id="correction-notes" class="level2" data-number="F.2">
<h2 data-number="F.2" class="anchored" data-anchor-id="correction-notes"><span class="header-section-number">F.2</span> Correction Notes</h2>
<p>These notes record the substantive interpretive and procedural corrections referenced in the change register, each flagged at the affected passages by footnote rather than by rewriting the defended text.</p>
<section id="sec-v1-1-h3b-note" class="level3" data-number="F.2.1">
<h3 data-number="F.2.1" class="anchored" data-anchor-id="sec-v1-1-h3b-note"><span class="header-section-number">F.2.1</span> v1.1 H3b Interpretation Correction Note</h3>
<p>The defended <span class="math inline">\(H_{3b}\)</span> discussion interprets the selected additive zero-inflated negative binomial model as if the effect of gap were additive and treatment-specific in slope. That is not correct. In the selected model, count-model effects are multiplicative on the log-link scale, and no gap-by-treatment interaction term is included. Accordingly, the model supports the conclusion that expected increases in UCE differ by treatment level across the observed retention intervals, with PWI lower than the reference AR condition. It does not support a claim that PWI changes the per-day rate of increase relative to AR, nor that treatment-specific decay slopes were estimated by the selected model.</p>
<p>This does not eliminate the <span class="math inline">\(H_{3b}\)</span> signal, but it narrows its interpretation. The defended phrasing about a lower rate of error increase should therefore be read as overstated. A more accurate reading is that the fitted model provides preliminary evidence of differences in expected retention-phase error increase by treatment, while leaving the mechanism of that difference, including whether treatments differ in slope over time, unresolved. To preserve the defended narrative, <code>v1.1</code> records that interpretive correction here and flags the affected passages in Results and Conclusions by footnote rather than rewriting them in place.</p>
<p>A related correction, added in the <code>v1.1.1</code> pass: the “Adj Coef” column in <a href="../_chaps/25-results.html#tbl-uce-modsum" class="quarto-xref">Table&nbsp;<span>5.24</span></a> halves every coefficient to undo the doubling that was applied to the response. That halving is right for the intercept, which is an expected count and so scales with the response, but not for the treatment coefficients. Each of those is a multiplicative rate ratio, and a rate ratio does not change when the response is rescaled, because the factor of two cancels between the two groups being compared; the coefficients should therefore be left as estimated, not halved. Read correctly, PWI’s expected error increase is 0.394 of the reference AR condition’s, not the halved 0.197: a shift in the overall level by treatment, consistent with the reading above, rather than a treatment-specific change in slope.</p>
</section>
<section id="sec-v1-1-reliance-note" class="level3" data-number="F.2.2">
<h3 data-number="F.2.2" class="anchored" data-anchor-id="sec-v1-1-reliance-note"><span class="header-section-number">F.2.2</span> v1.1.1 H2b Reliance Direction Correction Note</h3>
<p>The recall-phase reliance discussion (<span class="math inline">\(H_{2b}\)</span>) describes the augmented conditions as <em>reducing</em> reliance on the paper work instructions relative to PWI. That direction is reversed. As reported, the Results summary states that “AR and MR reduce reliance by 0.686 and 0.612 seconds per reference … relative to the PWI instructional method” and that “AR and MR … reduce reliance more than PAR and PWI,” and the Conclusions restate this as “reduced reliance on instructions for AR and MR users” (recall results-summary table; recall interpretation; Collective Insights).</p>
<p>The underlying bootstrap table (<a href="../_chaps/25-results.html#tbl-boot-pwi" class="quarto-xref">Table&nbsp;<span>5.18</span></a>) is correct; the prose reads it backward. The pairwise differences are signed as PWI minus treatment and are negative for the augmented conditions (the mean difference is about -0.99 s for PWI versus AR and -0.88 s for PWI versus MR; the median and Hodges-Lehmann contrasts agree), so PWI sits at the low end of paper reliance, not the high end. Recomputed group reliance during recall confirms this on every measure (average references per task, total reference time per task, and time per reference), with PWI and PAR lowest and the head-mounted AR and MR conditions highest. The simplest measure agrees: the share of participants who never consulted paper at recall was PWI 57%, PAR 50%, AR 31%, MR 29%, so the augmented (particularly head-mounted) learners were the more likely to reference the instructions. The printed values 0.686 and 0.612 do not appear in <a href="../_chaps/25-results.html#tbl-boot-pwi" class="quarto-xref">Table&nbsp;<span>5.18</span></a> and are not the reliance differences.</p>
<p>This does not change the <span class="math inline">\(H_{2b}\)</span> determination (reliance does vary with instructional method), and the Results caution that the specific pairwise differences are “not clear enough to declare” continues to govern. Reliance was low and heavily zero-weighted (143 of 212 recall tasks, and 22 of 53 participants, recorded no paper reference at all), so the comparison rests on a small number of referencers at modest per-group sample sizes. But the <em>direction</em> of the comparison was stated backward, and the interpretation it supports is affected: the recall reliance evidence does not indicate greater independence for the augmented conditions and, to the extent it points anywhere, indicates <em>greater</em> paper reliance at recall for the head-mounted AR and MR conditions. The defended learning-quality (<span class="math inline">\(H_{1c}\)</span>) and recall-performance (<span class="math inline">\(H_{2a}\)</span>) results do not depend on this measure and are unchanged. Per the errata-not-revision policy, the defended text and the (correct) table are left in place; this note records the correction and the affected passages are flagged by footnote.</p>
<p>Affected passages: in Results, the <span class="math inline">\(H_{2b}\)</span> bootstrap summary and Result; in Conclusions, the recall results-summary table (<span class="math inline">\(H_{2b}\)</span> row), the recall interpretation, and Collective Insights.</p>
</section>
<section id="sec-v1-1-boot-note" class="level3" data-number="F.2.3">
<h3 data-number="F.2.3" class="anchored" data-anchor-id="sec-v1-1-boot-note"><span class="header-section-number">F.2.3</span> v1.1.1 Bootstrap Replication Seeding Correction Note</h3>
<p>The <code>H2a</code> (OEE) and <code>H2b</code> (PWI reliance) complementary bootstrap analyses were described as five replications of 10,000 resamples each, averaged across replications, with the across-replication dispersion of bias and standard error reported as evidence of stability (the <code>sd_Bias</code> and <code>sd_SE</code> columns in <a href="../_chaps/25-results.html#tbl-boot-oee" class="quarto-xref">Table&nbsp;<span>5.16</span></a> and <a href="../_chaps/25-results.html#tbl-boot-pwi" class="quarto-xref">Table&nbsp;<span>5.18</span></a>). A seeding error made those five replications identical: the random seed was reset to the same fixed value immediately before each resampling call, so every replication drew the same resamples. Consequently, the averaging across replications was a no-op, and the reported across-replication dispersion is structurally zero rather than a measured quantity. The “five replications … averaged” description and the appeal to low across-replicate dispersion as evidence of reliability are therefore not supported as written.</p>
<p>This does not change the estimates or the conclusions. The tabulated differences, confidence intervals, biases, and standard errors are exactly those of a single valid 10,000-resample percentile bootstrap, which is itself a legitimate analysis; only the replication framing and the zero-valued dispersion columns are affected. The reported pairwise differences are deterministic functions of the full sample and do not depend on the seed. The primary inferences for both hypotheses rest on the Kruskal-Wallis tests, which are independent of this bootstrap, and the bootstrap is reported only as a complementary robustness check. The <code>H2a</code> and <code>H2b</code> results and their interpretations therefore stand as defended.</p>
<p>A corrected implementation, using a single high-resolution bootstrap without the per-replication reseed, is carried in follow-on work derived from this dissertation; it reproduces the same pattern of pairwise differences and leaves the substantive findings unchanged.</p>
<p>A related correction, added in the <code>v1.1.1</code> pass: the introduction to this analysis states that the replication process “effectively increases the sample size and statistical power of the analysis.” Resampling does neither. The bootstrap reuses the observed data, so it adds no information and cannot raise the effective sample size or the power to detect an effect; both are fixed by the number of participants and the size of the observed effect. Additional resamples improve only the precision with which the sampling distribution and its confidence intervals are estimated (lower Monte Carlo error), not the power of the analysis.</p>
</section>
</section>
<section id="interpretation-boundaries" class="level2" data-number="F.3">
<h2 data-number="F.3" class="anchored" data-anchor-id="interpretation-boundaries"><span class="header-section-number">F.3</span> Interpretation Boundaries</h2>
<ul>
<li>No new participants, data, or analyses were added for <code>v1.1</code> or <code>v1.1.1</code>.</li>
<li>The most substantive corrections are the Methods/Results retention reconciliation (<code>v1.1</code>) and the corrected direction of the recall reliance comparison (<code>v1.1.1</code>; see the H2b reliance note above).</li>
<li>Other changes in these passes are editorial, render-related, or transparency-related.</li>
</ul>
</section>
<section id="intentional-deferrals" class="level2" data-number="F.4">
<h2 data-number="F.4" class="anchored" data-anchor-id="intentional-deferrals"><span class="header-section-number">F.4</span> Intentional Deferrals</h2>
<p>The <code>v1.1</code> and <code>v1.1.1</code> releases are correction, reconciliation, and publication-safety passes, not a substantive revision of the defended dissertation. Several issues identified during review were therefore left unchanged by design. These include:</p>
<ul>
<li>broader rhetorical tightening of <code>H2b</code> and retention claims beyond the specific corrections documented above</li>
<li>new sensitivity analyses or robustness checks for exclusions, outliers, or model choices</li>
<li>broader revision of the qualitative-analysis method or its presentation</li>
<li>deeper softening of appendix material beyond visible public-facing draft residue and link/provenance fixes</li>
<li>a full audit of all inline statistics beyond the specific exposed reporting errors corrected in these passes</li>
</ul>
<p>These items were judged to fall outside the intended scope of an errata-style release. Where appropriate, they are better addressed in future paper manuscripts, follow-on analysis, or later revision work rather than in the corrected dissertation release itself.</p>
</section>
<section id="repository-diff" class="level2" data-number="F.5">
<h2 data-number="F.5" class="anchored" data-anchor-id="repository-diff"><span class="header-section-number">F.5</span> Repository Diff</h2>
<p>A repository compare view between the defended baseline tag and the <code>v1.1</code> release tag is available on GitHub:</p>
<ul>
<li><a href="https://github.com/olearydj/au_diss/compare/baseline%2Fdissertation-defended-2024-08-02...v1.1">baseline/dissertation-defended-2024-08-02…v1.1</a></li>
</ul>
<p>The additional <code>v1.1.1</code> corrections relative to <code>v1.1</code>:</p>
<ul>
<li><a href="https://github.com/olearydj/au_diss/compare/v1.1...v1.1.1">v1.1…v1.1.1</a></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../_apps/31a-irb.html" class="pagination-link" aria-label="Institutional Review Board Approval">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Institutional Review Board Approval</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>